ALTER TABLE `Product` ADD COLUMN `caseQty` INT NULL;
ALTER TABLE `Product` ADD COLUMN `color` VARCHAR(100) NULL;
ALTER TABLE `Product` ADD COLUMN `length` DECIMAL(10, 2) NULL;
ALTER TABLE `Product` ADD COLUMN `height` DECIMAL(10, 2) NULL;
ALTER TABLE `Product` ADD COLUMN `width` DECIMAL(10, 2) NULL;
ALTER TABLE `Product` ADD COLUMN `lastPriceChange` VARCHAR(100) NULL;
